/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=test/cloudflare/wrangler.jsonc --include-runtime=false test/cloudflare/environment.d.ts` (hash: 30c3823992a5154da09c838c96a8f2fb)
interface __BaseEnv_Env {
  ACTORS: DurableObjectNamespace<import("./worker").Actors>
  SESSIONS: DurableObjectNamespace<import("./worker").Sessions>
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker")
    durableNamespaces: "Actors" | "Sessions"
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
